kubernetesClusterDomain: cluster.local

mydata:
  mongoUsername: "mongo"
  mongoPassword: "mongo"
  mongoUrl: "mongo.mongo.svc.cluster.local"
  cookieSecret: "sdegrfkefw8t6732rbugwdqat8"

replicaCount: 3
strategy:
  type: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0

service:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000

pvc:
  PersistentStorage:
    storageClass: nfs-client
    storageRequest: 10G

image:
  repository: ghcr.io/ddung1203/youtube
  tag: latest
  PullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 500m
    memory: 1G

livenessProbe:
  httpGet:
    path: /health-check
    port: 4000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /health-check
    port: 4000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 5

hpa:
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
